# src/main/resources/application.yml
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/foro_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: foro
    password: "Foro#2025!"
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

app:
  jwt:
    secret: "cambia-esta-clave-super-secreta"
    expiration: 3600000
